### ISSUE TITLE
Update docs to remove references to DB download URL and add DB update workflow example

### ISSUE THREAD

**Issue by crozzy** [quay/clair-action#117]
As we made the decision not to host pre-compiled DB files for legal and maintenance reasons, we must update the README examples to correctly reflect the current state of affairs and let users know how they can create the DB themselves.

**Comment by janisz** [comment]
>  for legal and maintenance reasons
Maintenance reasons are quite obvious but I'm curios about legal? Could you explain it more?

**Comment by TommyTran732** [comment]
It's been awhile. Is there any chance you can provide the instructions on how to do do this any time soon?

**Comment by crozzy** [comment]
Yep, will be working on this at the beginning of this week

**Comment by crozzy** [comment]
https://github.com/quay/clair-action/pull/163 I updated some docs and some examples and verified the tekton pipelines work when generating your own DB. The DB creation process is latent hence why it is recreated periodically outside of the CI "run" lifecycle.

**Comment by hdonnay** [comment]
> Maintenance reasons are quite obvious but I'm curios about legal? Could you explain it please?

Redistributing vulnerability data needs to comply with the license terms for that data, which we don't have the expertise to evaluate.
