### ISSUE TITLE
parent command [clair-action] has duplicated subcommand name or alias: r

### ISSUE THREAD

**Issue by janisz** [quay/clair-action#122]
Action not working on master
```
./clair-action --help
2024/02/01 14:14:22 parent command [clair-action] has duplicated subcommand name or alias: r
```

Bisecting: 0 revisions left to test after this (roughly 1 step)
[ba8d3932310c01b201f420fd819f07c5cbd422bc] build(deps): bump github.com/urfave/cli/v2 from 2.25.7 to 2.27.1

**Comment by crozzy** [comment]
Addressed in https://github.com/quay/clair-action/pull/134 thanks!
